[package]
name = "ceros-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html



[dependencies]
acid_io = { git = "ssh://git@github.com/Culpeper-Robotics/acid_io.git", optional=true }
ceros-serial = { git = "ssh://git@github.com/Culpeper-Robotics/ceros-serial", optional = true}
ceros-macro = { git = "ssh://git@github.com/Culpeper-Robotics/ceros-macro" }
newlib-alloc = { version = "0.1.0", optional = true }
vexv5rt = { git = "ssh://git@github.com/Culpeper-Robotics/vexv5rt" }

[features]
default = ["alloc", "panic", "print", "serial", "green_threads"]
alloc = ["dep:newlib-alloc"]
serial = ["dep:ceros-serial", "dep:acid_io"]
panic = ["serial"]
print = ["serial"]
green_threads = []

[profile.dev]
panic = "abort"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"